const os = require('os')

console.log(os.homedir())
console.log(os.arch())
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.version())
console.log(os.platform())
console.log(os.hostname())
console.log(os.machine())